<?php
$tmp_date = date("Ym");
$year = substr($tmp_date,0,4);
$month = substr($tmp_date,4,2);
$nextmonth = mktime(0,0,0,$month+1,1,$year);
$next_tmp_date = date("Ym",$nextmonth);
$next_year = substr($next_tmp_date,0,4);
$next_month = substr($next_tmp_date,4,2);

$week = date_table($year, $month);
$next_week = date_table($next_year, $next_month);

function date_table($year, $month) {
	$day = date('j');
	$firstDay = date ('w', mktime (0, 0, 0, $month, 1, $year));
	$daysInMonth = date ('t', mktime(0, 0, 0, $month, 1, $year));
	$tempDays = $firstDay + $daysInMonth;  
	$weeksInMonth = ceil($tempDays/7);  
	$counter = 0;
	for($j = 0; $j < $weeksInMonth; $j ++) {
		for($i = 0; $i < 7; $i ++) {
			$counter++;
			$week[$j][$i] = $counter;
			//offset the days
			$week[$j][$i] -= $firstDay;
			if (($week[$j][$i] < 1) || ($week[$j][$i] > $daysInMonth)) {
				$week[$j][$i] = "";
			}
		}
	}
	return $week;
}
?>
<div style="margin-top:10px; height:460px; border:1px #D2D2D2 solid; " class="date">
<h5 class="dtitle">営業カレンダー</h5>
<div class="calender">
<table>
	<caption class="month"><?php echo $year.'年'.$month.'月の定休日';?></caption> 
	<thead>
    <tr>
        <th>日</th>
        <th>月</th>
        <th>火</th>
        <th>水</th>
        <th>木</th>
        <th>金</th>
        <th>土</th>
    </tr>
	</thead> 
	<tbody>
	<?php
	foreach ($week as $key => $val) {
		echo "<tr>";
		for($i = 0; $i < 7; $i++) {
			$weekend = ($i == 0 || $i == 6) ? 'class="off"' : '';
			echo "<td $weekend>$val[$i]</td>";
		}
		echo "</tr>";
	}
	?>
	</tbody>
</table>

<table class="nextdate">
	<caption class="month"><?php echo $next_year.'年'.$next_month.'月の定休日';?></caption> 
	<thead>
    <tr>
        <th>日</th>
        <th>月</th>
        <th>火</th>
        <th>水</th>
        <th>木</th>
        <th>金</th>
        <th>土</th>
    </tr>
	</thead> 
	<tbody>
	<?php
	foreach ($next_week as $key => $val) {
		echo "<tr>";
		for($i = 0; $i < 7; $i++) {
			$weekend = ($i == 0 || $i == 6) ? 'class="off"' : '';
			echo "<td $weekend>$val[$i]</td>";
		}
		echo "</tr>";
	}
	?>
	</tbody>
</table>

<div class="information">※赤字は休業日です</div>
<div class="information">※営業時間は9：00～17：00です</div>
</div>
</div>
