<?php

include_once '/app/code/core/Mage/Customer/controllers/AccountController.php';

//获取当前分类的所有子分类的模型集合
$categoryid = 3; // this sale category id
$collection = Mage::getModel('catalog/category')->getCategories($categoryid);

//循环子分类的模型集合
$childs = array();
foreach($collection as $cat) {
    if($cat->getIsActive()) {
        $category = Mage::getModel('catalog/category')->load($cat->getEntityId());
        //获取子分类的产品Collection，并通过count()方法，获取该子分类的产品数量
        //$prodCollection = Mage::getResourceModel('catalog/product_collection')->addCategoryFilter($category);
        //Mage::getSingleton('catalog/product_status')->addVisibleFilterToCollection($prodCollection);
        //Mage::getSingleton('catalog/product_visibility')->addVisibleInCatalogFilterToCollection($prodCollection);
		$childs[$cat->getEntityId()]['name'] = $category->getName();
		$childs[$cat->getEntityId()]['url'] = $category->getUrl();
    }
}
?>

<div class="block block-layered-nav">
	<div class="block-content">
		<dl id="narrow-by-list2">
			<dd>
				<ol>
				<?php foreach ($childs as $item) { ?>
					<a href="<?php echo $item['url'];?>"><li><?php echo $item['name'];?></li></a>
				<?php } ?>
				</ol>
			</dd>
		</dl>
	</div>
</div>
