<?php

/**
 * Implementation of hook_menu()
 * @return array
 */
function covidien_alert_menu() {
  $items = array();
  $items['alert/template/list'] = array(
    'page callback' => 'alert_template_list',
    'access callback' => 'covidien_alert_check_access',
    'type' => MENU_CALLBACK,
  );
  $items['alert/template/add'] = array(
    'page callback' => 'alert_template_add',
    'access callback' => 'covidien_alert_check_access',
    'type' => MENU_CALLBACK,
  );
  $items['alert/template/edit/%'] = array(
    'page callback' => 'alert_template_edit',
    'page arguments' => array(3),
    'access callback' => 'covidien_alert_check_access',
    'type' => MENU_CALLBACK,
  );
  $items['alert/ajax/checkName'] = array(
    'page callback' => 'alert_ajax_check_name',
    'access callback' => 'covidien_alert_check_access',
    'type' => MENU_CALLBACK,
  );
  $items['alert/template/delete'] = array(
    'page callback' => 'alert_template_delete',
    'access callback' => 'covidien_alert_check_access',
    'type' => MENU_CALLBACK,
  );
  $items['alert/config/list'] = array(
    'page callback' => 'alert_config_list',
    'access callback' => 'is_login_user',
    'title' => t('Alerts'),
    'type' => MENU_CALLBACK,
  );
  $items['alert/config/subscribe/%'] = array(
    'page callback' => 'alert_config_subscribe',
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );
  $items['alert/config/edit/%'] = array(
    'page callback' => 'alert_config_edit',
    'access callback' => 'covidien_alert_edit_check_access',
    'type' => MENU_CALLBACK,
  );
  $items['alert/comment/%/delete/%'] = array(
    'page callback' => 'alert_comment_delete',
    'access callback' => 'covidien_alert_check_access',
    'type' => MENU_CALLBACK,
  );
  $items['alert/ajax/get_app_role_list'] = array(
    'page callback' => 'covidien_alert_get_app_role_list',
    'access callback' => 'covidien_alert_check_access',
  );
  $items['alert/ajax/get_template_tbl'] = array(
    'page callback' => 'covidien_alert_ajax_get_template_tbl',
    'access callback' => 'covidien_alert_check_access',
  );
  $items['alert/config/subscribeSave'] = array(
    'page callback' => 'covidien_alert_subscribe_save',
    'access callback' => 'is_login_user',
    'type' => MENU_CALLBACK,
  );
  $items['alert/ajax/get_alert_event_list'] = array(
    'page callback' => 'covidien_alert_ajax_get_alert_event_list',
    'access callback' => 'covidien_alert_check_access',
  );
  $items['alert/ajax/get_alert_event_status_tbl'] = array(
    'page callback' => 'covidien_alert_ajax_get_alert_event_status_tbl',
    'access callback' => 'covidien_alert_check_access',
  );
  $items['alert/ajax/get_person_alert_event'] = array(
    'page callback' => 'covidien_alert_ajax_get_person_alert_event',
    'access callback' => 'is_login_user',
  );
  $items['alert/ajax/get_person_alert_country'] = array(
    'page callback' => 'covidien_alert_ajax_get_person_alert_country',
    'access callback' => 'is_login_user',
  );
  $items['alert/ajax/get_person_alert_delivery'] = array(
    'page callback' => 'covidien_alert_ajax_get_person_alert_delivery',
    'access callback' => 'is_login_user',
  );
  $items['alert/notification/list'] = array(
    'page callback' => 'alert_notification_list',
    'access callback' => 'covidien_alert_check_access',
    'title' => t('Alerts'),
    'type' => MENU_CALLBACK,
    'file' => 'covidien_alert.notification.inc',
  );
  $items['alert/notification/add'] = array(
    'page callback' => 'alert_notification_add',
    'access callback' => 'isAdmin',
    'title' => t('Alerts'),
    'type' => MENU_CALLBACK,
    'file' => 'covidien_alert.notification.inc',
  );
  $items['alert/notification/edit/%'] = array(
    'page callback' => 'alert_notification_edit',
    'access callback' => 'covidien_alert_check_access',
    'title' => t('Alerts'),
    'type' => MENU_CALLBACK,
    'file' => 'covidien_alert.notification.inc',
  );
  $items['alert/notification/save'] = array(
    'page callback' => 'alert_notification_save_form',
    'access callback' => 'isAdmin',
    'title' => t('Alerts'),
    'type' => MENU_CALLBACK,
    'file' => 'covidien_alert.notification.inc',
  );
  $items['alert/notification/ajax/save'] = array(
    'page callback' => 'alert_notification_ajax_save',
    'access callback' => 'isAdmin',
    'title' => t('Alerts'),
    'type' => MENU_CALLBACK,
    'file' => 'covidien_alert.notification.inc',
  );
  $items['alert/notification/schedule/%/add'] = array(
    'page callback' => 'technical_notification_schedule_save',
    'access callback' => 'isAdmin',
    'title' => t('Alerts'),
    'type' => MENU_CALLBACK,
    'file' => 'covidien_alert.notification.inc',
  );
  $items['alert/notification/schedule/%/edit/%'] = array(
    'page callback' => 'technical_notification_schedule_save',
    'access callback' => 'isAdmin',
    'title' => t('Alerts'),
    'type' => MENU_CALLBACK,
    'file' => 'covidien_alert.notification.inc',
  );
  $items['alert/notification/schedule/%/delete/%'] = array(
    'page callback' => 'technical_notification_schedule_delete',
    'access callback' => 'isAdmin',
    'title' => t('Alerts'),
    'type' => MENU_CALLBACK,
    'file' => 'covidien_alert.notification.inc',
  );
  $items['alert/notification-history/list'] = array(
    'page callback' => 'alert_notification_history_list',
    'access callback' => 'covidien_alert_check_access',
    'title' => t('Alerts'),
    'type' => MENU_CALLBACK,
    'file' => 'covidien_alert.notification.inc',
  );
  $items['alert/notification-history/view/%'] = array(
    'page callback' => 'alert_notification_history_view',
    'access callback' => 'covidien_alert_check_access',
    'title' => t('Alerts'),
    'type' => MENU_CALLBACK,
    'file' => 'covidien_alert.notification.inc',
  );
  return $items;
}

/**
 * Implementation of hook_init()
 */
function covidien_alert_init() {
  module_load_include('module', 'covidien_firmware');
  module_load_include('php', 'covidien_alert', 'covidien_alert_helper.php');
  module_load_include('inc', 'covidien_alert', 'covidien_alert.notification');
}

/**
 * access callback
 * @global type $user
 * @return boolean
 */
function isAdmin() {
  global $user;
  if ($user->uid == 1) {
    return true;
  } else {
    return false;
  }
}

/**
 * implementation of hook_theme()
 * @return type
 */
function covidien_alert_theme() {
  $alert_theme = array(
    'alert_template_list' => array(
      'template' => 'alert_template_list',
      'arguments' => array('form' => NULL, 'get' => NULL),
    ),
    'alert_template_form' => array(
      'template' => 'alert_template_form',
      'arguments' => array('form' => NULL, 'get' => NULL),
    ),
    'alert_config_list' => array(
      'template' => 'alert_config_list',
      'arguments' => array('form' => NULL, 'get' => NULL),
    ),
    'alert_config_subscribe' => array(
      'template' => 'alert_config_subscribe',
      'arguments' => array('form' => NULL, 'get' => NULL),
    ),
    'alert_config_form' => array(
      'template' => 'alert_config_form',
      'arguments' => array('form' => NULL, 'get' => NULL),
    ),
    'alert_notification_list' => array(
      'template' => 'alert_notification_list',
      'arguments' => array('form' => NULL, 'get' => NULL),
    ),
    'alert_notification_form' => array(
      'template' => 'alert_notification_form',
      'arguments' => array('form' => NULL, 'get' => NULL),
    ),
    'technical_notification_schedule_form' => array(
      'template' => 'technical_notification_schedule_form',
      'arguments' => array('form' => NULL, 'get' => NULL),
    ),
    'alert_notification_history_list' => array(
      'template' => 'alert_notification_history_list',
      'arguments' => array('form' => NULL, 'get' => NULL),
    ),
  );
  return $alert_theme;
}

function covidien_alert_check_access() {
  return covidien_cot_admin_access_callback('alert');
}

function covidien_alert_edit_check_access() {
  global $user;
  $flag = false;
  if (covidien_cot_admin_access_callback('alert')) {
    if ($user->covidien_user == 'Yes') {
      $flag = true;
    } else {
      $sql = "select d.field_person_username_value from alert a join node b on a.device_nid = b.nid 
      join content_type_device c on b.nid = c.nid and b.vid = c.vid 
      join content_type_person d on c.field_device_owner_nid = d.field_comp_account_no_nid 
      and d.field_person_username_value = '%s' where a.id = %d ";
      $result = db_query($sql, $user->mail, arg(3));
      if ($row = db_fetch_object($result)) {
        $flag = true;
      }
    }
  }
  return $flag;
}

function alert_template_list() {
  drupal_set_title(t('Alert template list'));
  $output = theme('alert_template_list');
  return $output;
}

function alert_template_add() {
  drupal_set_title(t('Add New Message Template'));
  alert_template_form_validate($form_stats);
  alert_template_form_submit($form_stats);
  $output = drupal_get_form('alert_template_form');
  return $output;
}

function alert_template_edit() {
  drupal_set_title(t('Edit Message Template'));
  alert_template_form_validate($form_stats);
  alert_template_form_submit($form_stats);
  return drupal_get_form('alert_template_form');
}

function alert_config_list() {
  drupal_set_title(t('Alerts'));
  $output = theme('alert_config_list');
  return $output;
}

function alert_config_subscribe() {
  $output = theme('alert_config_subscribe');
  return $output;
}

function alert_config_edit() {
  alert_config_form_submit($form_stats);
  $output = drupal_get_form('alert_config_form');
  return $output;
}

function alert_config_edit_save() {
  return $output;
}

/**
 * Implementation of hook_form()
 * @return array
 */
function alert_config_form() {
  $form = array();
  unset($alert_status_option[0]);
  $aid = arg(3);
  $alert = array();
  if ($aid) {
    $alert_result = db_query("SELECT alert_state_id FROM {alert} WHERE id = %d", $aid);
    $alert['status_id'] = db_fetch_object($alert_result)->alert_state_id;
  }
  $alert_status_option = _get_alert_state_list($alert['status_id']);
  $form['#theme'] = 'alert_config_form';
  $form['alert_id'] = array(
    '#type' => 'hidden',
    '#value' => $aid,
  );
  $form['sel_alert_status'] = array(
    '#type' => 'select',
    '#id' => 'sel_alert_status',
    '#name' => 'sel_alert_status',
    '#options' => $alert_status_option,
    '#default_value' => $alert['status_id'],
    '#value' => $alert['status_id'],
  );
  $form['comment_id'] = array(
    '#type' => 'hidden',
    '#value' => '',
  );
  $form['alert_comment'] = array(
    '#type' => 'textarea',
    '#id' => 'alert_comment',
    '#name' => 'alert_comment',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save Change'),
    '#id' => 'btn-submit',
  );
  return $form;
}

/**
 * Implementation of hook_form_submit()
 * @global type $user
 * @param type $form_stats
 * @return boolean
 */
function alert_config_form_submit(&$form_stats) {
  if (count(form_get_errors()) || !$_POST['op']) {
    return false;
  }
  $post = filter_xss_arr($_POST);
  if ($post['alertCategory'] == 'Informational alert') {
    return false;
  }
  global $user;
  $alert_id = $post['alert_id'];
  $alert_status = $post['sel_alert_status'];
  $comment = $post['alert_comment'];
  $comment_id = $post['comment_id'];

  $status_rows = _get_alert_state_list();
  $old_status = db_result(db_query("SELECT alert_state_id FROM {alert} WHERE id=%d", $alert_id));

  $now = time();
  $date = format_date($now, 'custom', 'Y-m-d H:i:s');
  db_query("UPDATE {alert} SET alert_state_id = %d, changed = %d WHERE id = %d", $alert_status, $now, $alert_id);
  //get user person nid
  $person_nid = db_result(db_query("SELECT n.nid FROM {node} n JOIN {users} u ON n.uid=u.uid AND n.type='person' WHERE u.uid=%d", $user->uid));
  if ($comment_id) {
    //edit comment
    $sql = "UPDATE {alert_comment} SET comment='%s', last_change_time='%s', person_nid=%d WHERE id=%d";
    db_query($sql, $comment, $date, $person_nid, $comment_id);
  } else {
    //insert comment
    $content = '';
    if ($status_rows[$old_status] != $status_rows[$alert_status]) {
      $content = 'Alert Status is changed from ' . $status_rows[$old_status] . ' to ' . $status_rows[$alert_status] . '<br/> ';
    }
    if (!empty($comment)) {
      $content .= " $comment";
    }
    if (!empty($content)) {
      $sql = "INSERT INTO {alert_comment} (alert_id, comment, create_time, person_nid, last_change_time) VALUES (%d, '%s', %d, %d, '%s')";
      db_query($sql, $alert_id, $content, $now, $person_nid, $date);
    }
  }

  drupal_goto('alert/config/list');
}

/**
 * Implementation of hook_form()
 * @return array
 */
function alert_template_form() {
  $id = arg(3);
  $alert_template = $id ? alert_get_template($id) : array();
  $form = array();
  if ($alert_template['device_type_id']) {
    $form_device_type = field_device_type_select($alert_template['device_type_id'], 'All');
    $form_device_type['select_device_type']['#options'] = array($alert_template['device_type_id'] => $form_device_type['select_device_type']['#options'][$alert_template['device_type_id']]);
  } else {
    $form_device_type = field_device_type_select($alert_template['device_type_id']);
    unset($form_device_type['select_device_type']['#options'][0]);
  }
  $form['sel_device_type'] = $form_device_type['select_device_type'];
  $form['template_name'] = array(
    '#type' => 'textfield',
    '#id' => 'template_name',
    '#name' => 'template_name',
    '#default_value' => $alert_template['name'],
    '#value' => $alert_template['name'],
  );
  $alert_category_option = _get_alert_category_list('yes');
  $sel_alert_category = $_GET['sel_alert_category'] ? check_plain($_GET['sel_alert_category']) : $alert_template['category_id'];
  $form['sel_alert_category'] = array(
    '#type' => 'select',
    '#id' => 'sel_alert_category',
    '#name' => 'sel_alert_category',
    '#options' => $alert_category_option,
    '#default_value' => $sel_alert_category,
    '#value' => $sel_alert_category,
  );
  $alert_event_option = _get_alert_event_list('All', 'yes');
  if ($alert_template['alert_event_id']) {
    $alert_event_option = array($alert_template['alert_event_id'] => $alert_event_option[$alert_template['alert_event_id']]);
  }
  $form['sel_alert_event'] = array(
    '#type' => 'select',
    '#id' => 'sel_alert_event',
    '#name' => 'sel_alert_event',
    '#options' => $alert_event_option,
    '#default_value' => $alert_template['alert_event_id'],
    '#value' => $alert_template['alert_event_id'],
  );
  $delivery_option = _get_alert_delivery_list();
  $form['sel_delivery'] = array(
    '#type' => 'select',
    '#id' => 'sel_delivery',
    '#name' => 'sel_delivery',
    '#options' => $delivery_option,
    '#default_value' => $alert_template['delivery_id'],
    '#value' => $alert_template['delivery_id'],
  );
  $template_content = file_exists($alert_template['template_path']) ? file_get_contents($alert_template['template_path']) : '';
  $form['template_content'] = array(
    '#type' => 'textarea',
    '#id' => 'template_content',
    '#name' => 'template_content',
    '#default_value' => $template_content,
    '#value' => $template_content,
  );
  $form['template_subject'] = array(
    '#type' => 'textfield',
    '#id' => 'template_subject',
    '#name' => 'template_subject',
    '#default_value' => $alert_template['message_subject'],
    '#value' => $alert_template['message_subject'],
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save Template'),
    '#id' => 'btn-submit',
    '#attributes' => array('disabled' => 'disabled', 'class' =>
      'non_active_blue'),
  );

  return $form;
}

function alert_template_form_validate(&$form_stats) {
  if (!$_POST['op']) {
    return false;
  }
  if (!covidien_ui_input_validate($_POST['template_name'], true)) {
    form_set_error('template_name', t('Invalid Template Name'));
  }
  if (!covidien_ui_input_validate($_POST['sel_alert_category'], true)) {
    form_set_error('sel_alert_category', t('Invalid Alert Category'));
  }
  if (!covidien_ui_input_validate($_POST['sel_alert_event'], true)) {
    form_set_error('sel_alert_event', t('Invalid Alert Event'));
  }
  if (!covidien_ui_input_validate($_POST['sel_delivery'], true)) {
    form_set_error('sel_delivery', t('Invalid Delivery'));
  }
  if (!covidien_ui_input_validate($_POST['template_content'], true)) {
    form_set_error('template_content', t('Invalid Template Content'));
  }
  if (!covidien_ui_input_validate($_POST['template_subject'], true)) {
    form_set_error('template_subject', t('Invalid Template Subject'));
  }
  $sql = "SELECT a.id FROM {alert_message_template} a
    JOIN {device_type_alert_template_relation} dt ON a.id = dt.alert_message_template_id
    WHERE dt.device_type_nid=%d AND a.alert_event_id=%d";
  $temp_id = db_result(db_query($sql, check_plain($_POST['field_device_type_nid']), check_plain($_POST['sel_alert_event'])));
  $id = arg(3);
  if ($temp_id && $temp_id != $id) {
    form_set_error('sel_alert_event', t('Duplicate Template'));
  }
}

function alert_template_form_submit(&$form_stats) {
  $post = filter_xss_arr($_POST);
  if (count(form_get_errors()) || !$post['op']) {
    return false;
  }
  $device_type_id = $post['field_device_type_nid'];
  $args['name'] = $post['template_name'];
  $args['alert_event_id'] = $post['sel_alert_event'] ? $post['sel_alert_event'] : 0;
  $args['delivery_id'] = $post['sel_delivery'] ? $post['sel_delivery'] : 0;
  $args['message_subject'] = $post['template_subject'];
  $template_content = $post['template_content'];
  $id = arg(3);
  if ($id) { //update
    db_query("UPDATE {device_type_alert_template_relation} SET device_type_nid=%d WHERE alert_message_template_id=%d", $device_type_id, $id);
    db_query("UPDATE {alert_message_template} SET name='%s', alert_event_id=%d, alert_transport_type_id=%d, message_subject_text='%s' WHERE id=%d", array_merge($args, array($id)));
    $message = '<em>' . $args['name'] . '</em> has been updated.';
  } else { //add
    db_query("INSERT INTO {alert_message_template} (name, alert_event_id, alert_transport_type_id, message_subject_text) VALUES ('%s', %d, %d, '%s')", $args);
    $id = db_last_insert_id('alert_message_template', 'id');
    db_query("INSERT INTO {device_type_alert_template_relation} (device_type_nid, alert_message_template_id) VALUES (%d, %d)", $device_type_id, $id);
    $message = '<em>' . $args['name'] . '</em> has been created.';
  }
  global $alert_template_path, $drupal_abs_path;
  $template_dir = file_directory_path() . '/' . $alert_template_path;
  if (file_check_directory($template_dir, FILE_CREATE_DIRECTORY)) {
    //remove message for creating directory.
    $_SESSION['messages'] = array();
    $template_path = $template_dir . '/alert_template_' . $args ['alert_event_id'] . '_' . $args['delivery_id'] . '_' . $id;
    file_put_contents($template_path, $template_content);
  }
  db_query("UPDATE {alert_message_template} SET template_path='%s' WHERE id=%d", $template_path, $id);
  drupal_set_message($message);
  drupal_goto('alert/template/list');
}

function alert_get_template($id) {
  $sql = "SELECT a.id, a.name, dt.device_type_nid AS device_type_id, a.alert_event_id, a.alert_transport_type_id AS delivery_id, 
      a.message_subject_text, ae.category_id, a.template_path
      FROM {alert_message_template} a
      JOIN {alert_transport_type} ty ON ty.id = a.alert_transport_type_id 
      JOIN {alert_event} ae ON ae.id = a.alert_event_id 
      JOIN {device_type_alert_template_relation} dt ON a.id = dt.alert_message_template_id
      WHERE a.id = %d";
  $result = db_query($sql, $id);
  $rows = array();
  while ($row = db_fetch_object($result)) {
    $rows['id'] = $row->id;
    $rows['device_type_id'] = $row->device_type_id;
    $rows['name'] = $row->name;
    $rows['category_id'] = $row->category_id;
    $rows['alert_event_id'] = $row->alert_event_id;
    $rows['delivery_id'] = $row->delivery_id;
    $rows['template_path'] = $row->template_path;
    $rows['message_subject'] = $row->message_subject_text;
  }
  return $rows;
}

function covidien_theme_preprocess_alert_template_list(&$vars) {
  $device_type_id = check_plain($_GET['field_device_type_nid']);
  $category_id = check_plain($_GET['sel_alert_category']);
  $product_line = $_SESSION['default_cot'];
  $sql = "SELECT a.id, a.name, dn.title AS device_type, ae.name AS alert_event, ty.name AS delivery, a.message_subject_text
      FROM {alert_message_template} a
      JOIN {alert_transport_type} ty ON ty.id = a.alert_transport_type_id 
      JOIN {alert_event} ae ON ae.id = a.alert_event_id 
      JOIN {device_type_alert_template_relation} dt ON a.id = dt.alert_message_template_id
      JOIN {content_field_device_product_line} dpl ON dpl.field_device_product_line_nid = %d
      and dpl.nid = dt.device_type_nid
      LEFT JOIN {node} dn ON dt.device_type_nid = dn.nid
      WHERE 1 ";
  $args = array();
  $args[] = $product_line;
  if ($device_type_id && $device_type_id != 'All') {
    $sql .= " AND dn.nid=%d ";
    $args[] = $device_type_id;
  }
  if ($category_id && $category_id != 'All') {
    $sql .= " AND ae.category_id=%d ";
    $args[] = $category_id;
  }
  $header = array(
    array('data' => t('Template Name'), 'field' => 'a.name', 'sort' => 'asc'),
    array('data' => t('Device Type'), 'field' => 'dn.title', 'sort' => 'asc'),
    array('data' => t('Alert Event'), 'field' => 'ae.name', 'sort' => 'desc'),
    array('data' => t('Dilivery'), 'field' => 'ty.name', 'sort' => 'desc'),
    array('data' => t('Subject Line'), 'field' => 'a.message_subject_text', 'sort' => 'asc'),
  );
  $sql .= tablesort_sql($header);
  $pageSize = 10;
  $result = pager_query($sql, $pageSize, 0, NULL, $args);

  //check edit access 
  $has_edit_access = check_user_has_edit_access('alert');

  while ($row = db_fetch_object($result)) {
    if ($has_edit_access) {
      $rows[$row->id]['name'] = l($row->name, 'alert/template/edit/' . $row->id);
    } else {
      $rows[$row->id]['name'] = $row->name;
    }
    $rows[$row->id]['device_type'] = $row->device_type;
    $rows[$row->id]['alert_event'] = $row->alert_event;
    $rows[$row->id]['delivery'] = $row->delivery;
    $rows[$row->id]['message_subject_text'] = $row->message_subject_text;
  }
  $table_list = '';
  $table_list .= theme_table($header, $rows);
  $table_list .= theme('pager', NULL, 10, 0);
  $form_device_type = field_device_type_select($device_type_id);
  $template_form = alert_template_form();
  $vars['sel_device_type'] = drupal_render($form_device_type['select_device_type']);
  $template_form['sel_alert_category']['#options'][0] = 'All';
  ksort($template_form['sel_alert_category']['#options']);
  $vars['sel_alert_category'] = drupal_render($template_form['sel_alert_category']);
  $vars['table_list'] = $table_list;
}

function covidien_theme_preprocess_alert_config_form(&$vars) {
  $aid = arg(3);
  $alert = array();
  if ($aid) {
    //alert information
    $sql = "SELECT a.id, dn.title AS device_type, d.title AS serial_number, t.name AS alert_event, c.name AS alert_category
        FROM {alert} a
        JOIN {node} dn ON a.device_type_nid = dn.nid
        JOIN {node} d ON a.device_nid = d.nid
        JOIN {alert_event} t ON a.alert_event_id = t.id
        JOIN {alert_category} c ON c.id = t.category_id 
        WHERE a.id = %d ";
    $result = db_query($sql, $aid);
    while ($row = db_fetch_object($result)) {
      $alert['alert_id'] = $row->id;
      $alert['device_type'] = $row->device_type;
      $alert['serial_number'] = $row->serial_number;
      $alert['alert_event'] = $row->alert_event;
      $alert['alert_category'] = $row->alert_category;
    }
  }

  $vars['alert'] = $alert;
  $vars['comments'] = alert_get_comments($aid);
}

/**
 * get comment by alert id
 * @param type $aid
 * @return string
 */
function alert_get_comments($aid) {
  if (!$aid) {
    return '';
  }
  //alert comments 
  $comment_sql = "SELECT c.id, c.person_nid, CONCAT(p.field_first_name_value, ' ', p.field_last_name_value) AS user_name, c.create_time, c.comment
      FROM {alert_comment} c 
      LEFT JOIN {node} pn ON c.person_nid = pn.nid
      LEFT JOIN {content_type_person} p ON pn.nid = p.nid AND pn.vid = p.vid
      WHERE c.alert_id = %d ";
  $comment_result = db_query($comment_sql, $aid);
  $comments = array();
  while ($comment_row = db_fetch_object($comment_result)) {
    $comments[$comment_row->id]['id'] = $comment_row->id;
    $comments[$comment_row->id]['person_nid'] = $comment_row->person_nid;
    $comments[$comment_row->id]['user_name'] = $comment_row->user_name;
    $comments[$comment_row->id]['create_time'] = $comment_row->create_time ? date('M/d/y h:i A', $comment_row->create_time) : '';
    $comments[$comment_row->id]['comment'] = $comment_row->comment;
  }
  if (!count($comments)) {
    return '';
  }
  //output
  $comment_output = '';
  foreach ($comments as $item) {
    $comment_output .= '<div class="alert-comment" id="comment-' . $item['id'] . '"><ul>';
    $comment_output .= '<li class="comment-link">';
    $comment_output .= l(t('Edit'), 'alert/comment/' . $item['id'] . '/edit', array('attributes' => array('id' => 'edit-comment-' . $item['id']))) . '&nbsp;&nbsp;';
    $comment_output .= l(t('Delete'), 'alert/comment/' . $aid . '/delete/' . $item['id'], array('attributes' => array('id' => 'delete-comment-' . $item['id']))) . '</li>';
    $person_title = $item['person_nid'] ? $item['user_name'] : user_load(1)->name;
    $person_link = $item['person_nid'] ? 'node/' . $item['person_nid'] . '/edit' : 'user/1/edit';
    $comment_output .= '<li>' . l($person_title, $person_link) . ' Add a comment - ' . $item['create_time'] . '</li>';
    $comment_output .= '<li class="comment-content"> ' . $item['comment'] . '</li>';
    $comment_output .= '</ul></div>';
  }

  return $comment_output;
}

/**
 * menu callback alert/comment/%/delete/%
 */
function alert_comment_delete() {
  $aid = arg(2);
  $cid = arg(4);
  db_query("DELETE FROM {alert_comment} WHERE id=%d", $cid);
  drupal_goto(
    'alert/config/edit/' . $aid);
}

function alert_template_delete() {
  $templateIdArr = $_REQUEST ['template-list-wedgit-chk'];

  if (!empty($templateIdArr)) {
    foreach ($templateIdArr as $value) {
      $tempalteId = $value;
      $sql = "select id from alert_type where template_id = '" . $tempalteId . "'";
      $result = db_query($sql);
      $type_id = db_fetch_object($result)->id;
      if (!empty($type_id)) {
        $sql = "select name from alert_email_template where id = '" . $tempalteId . "'";
        $result = db_query($sql);
        $tempalteName = db_fetch_object($result)->name;
        drupal_set_message('Cannot delete the template: ' . $tempalteName . ', because it reference an alert type!', 'error');
      } else {
        $sql = "select template_path from alert_email_template where id = '" . $tempalteId . "'";
        $result = db_query($sql);
        $tempaltePath = db_fetch_object($result)->template_path;
        if (!empty($tempaltePath)) {
          unlink($tempaltePath);
        }
        $sql = "delete from alert_email_template where id = '" . $tempalteId . "'";
        db_query($sql);
      }
    }
  } else {
    drupal_set_message('No item be selected to delete!	', 'error');
  } $targetUrl = str_replace('delete', 'list', $_SERVER ['REQUEST_URI']);
  header(
    "Location: " . $targetUrl);
}

function alert_ajax_check_name() {
  $name = check_plain($_GET['txt_name']);
  $result = db_query("SELECT count(*) AS count FROM alert_email_template WHERE name = '%s'", $name);
  $count = db_fetch_object($result)->count;
  if (!empty($count)) {
    if ($count > 0) {
      echo '1';
    } else {
      echo '0';
    }
  } else {

    echo '0';
  }
  exit();
}

function covidien_theme_preprocess_alert_config_list(&$vars) {
  global $user;
// sql need to customize
  $product_line = $_SESSION['default_cot'];
  $sql = "SELECT a.id, d.title AS device, dtn.title AS device_type_name, 
        e.name AS event, s.name AS status, a.create_datetime, a.changed
        FROM {alert} a
        JOIN {content_field_device_product_line} dpl ON dpl.nid = a.device_type_nid
        JOIN {alert_event} e ON e.id = a.alert_event_id
        JOIN {alert_category} AS act ON e.category_id = act.id
        JOIN {alert_state} s ON s.id = a.alert_state_id 
        JOIN {node} dtn ON dtn.nid = a.device_type_nid
        JOIN {node} d ON a.device_nid = d.nid
        LEFT JOIN {alert_state_history} ash ON a.id = ash.alert_id AND a.alert_state_id = ash.alert_state_id ";
  $args = array();
  if ($user->covidien_user != 'Yes') {
    $sql .= " join content_type_device device on device.nid = d.nid and device.vid = d.vid
    	join content_type_person person on person.field_comp_account_no_nid = device.field_device_owner_nid
    	and person.field_person_username_value = '%s' ";
    $args[] = $user->mail;
  }
  $sql .= "WHERE act.name <> 'General Notification' AND dpl.field_device_product_line_nid = %d ";
  $args[] = $product_line;

  // sql extends start
  $event_id = check_plain($_GET['alert_event']);
  $status_id = check_plain($_GET['alert_state']);
  $device_type_id = check_plain($_GET['field_device_type_nid']);
  if ($event_id && $event_id != 'All') {
    $sql .= " AND a.alert_event_id = %d ";
    $args[] = $event_id;
  }
  if ($status_id && $status_id != 'All') {
    $sql .= " AND a.alert_state_id = %d ";
    $args[] = $status_id;
  }
  if ($device_type_id && $device_type_id != 'All') {
    $sql .= " AND a.device_type_nid = %d ";
    $args[] = $device_type_id;
  }
  // sql extends end
  // table head need to customize
  $header = array(
    array('data' => t('Serial Number'), 'field' => 'd.title'),
    array('data' => t('Device Type'), 'field' => 'dtn.title'),
    array('data' => t('Alert Event'), 'field' => 'e.name'),
    array('data' => t('Alert Status'), 'field' => 's.name'),
    array('data' => t('Date Created'), 'field' => 'a.create_datetime', 'sort' => 'desc'),
    array('data' => t('Date Updated'), 'field' => 'a.changed'),
  );
  $page_size = 10;
  $count_query = "SELECT count(*) FROM ($sql) AS count_query";
  $sql .= tablesort_sql($header);

  $result = pager_query($sql, $page_size, 0, $count_query, $args);
  $rows = array();

  //check edit access 
  $has_edit_access = check_user_has_edit_access('alert');

  while ($row = db_fetch_object($result)) {
    if ($has_edit_access) {
      $rows[$row->id]['serial_number'] = l($row->device, 'alert/config/edit/' . $row->id);
    } else {
      $rows[$row->id]['serial_number'] = $row->device;
    }
    $rows[$row->id]['device_type_name'] = $row->device_type_name;
    $rows[$row->id]['event'] = $row->event;
    $rows[$row->id]['status'] = $row->status;
    $rows[$row->id]['create_datetime'] = $row->create_datetime;
    $rows[$row->id]['update_datetime'] = $row->changed ? format_date($row->changed, 'custom', 'Y-m-d H:i:s') : '';
  }
  $table_list = theme_table($header, $rows);
  $table_list .= theme('pager', NULL, $page_size, 0);
  $form_device_type = field_device_type_select($device_type_id);
  $filter_form = _filter_alert_select_form();
  $filter_form['alert_event']['#options'][0] = 'All';
  $filter_form['alert_state']['#options'][0] = 'All';
  ksort($filter_form['alert_event']['#options']);
  ksort($filter_form['alert_state']['#options']);
  $vars['sel_device_type'] = drupal_render($form_device_type['select_device_type']);
  $vars['sel_alert_event'] = drupal_render($filter_form['alert_event']);
  $vars['sel_alert_state'] = drupal_render($filter_form['alert_state']);
  $vars['table_list'] = $table_list;
}

function covidien_theme_preprocess_alert_template_form(&$vars) {
  
}

function covidien_theme_preprocess_alert_config_subscribe(&$vars) {
  global $user;
  $uid = $user->uid;
  $page = arg(3);
  $form = _filter_alert_select_form();
  drupal_set_title(t('Alert Subscription Administration'));
  $alert_from = alert_config_form();
  $vars['select_deivce_type'] = drupal_render($form['select_device_type']);
  $vars['select_alert_category'] = drupal_render($form['alert_category']);
  $vars['select_alert_event'] = drupal_render($form['alert_event']);
  $vars['select_alert_delivery'] = drupal_render($form['alert_delivery']);
  $vars['form_submit'] = drupal_render($alert_from['submit']);
  $subscriptionType = array();
  if (!is_cot_admin()) {
    $vars['subscription_page'] = 'personal';
    $subscriptionType['personal'] = 'checked';
  } else {
    $vars['subscription_page'] = $page;
    $subscriptionType[$page] = 'checked';
  }
  $vars['subscriptionType'] = $subscriptionType;
}

function covidien_alert_subscribe_save() {
  global $user;
  $uid = $user->uid;
  $post = filter_xss_arr($_POST);
  $operation_type = $post['operationType'];
  try {
    $device_type_id = $post['sel_device_type'];
    $alert_category = $post['alert_category'];
    $subscriptionType = $post['subscriptionType'];
    if ($uid == 1 || $subscriptionType == 'A') {
      if ($operation_type == 'N') {
        $enable_event_list = is_array($post['field_alert_event_status_list']) ? $post['field_alert_event_status_list'] : array();
        $sql_query_exsit = 'select id from device_type_alert_event_relation where alert_event_id = %d and device_type_nid = %d';
        $sql_update = "update device_type_alert_event_relation set enable_flag = '%s' where id = %d";
        $sql_insert = "insert into device_type_alert_event_relation (device_type_nid,alert_event_id,enable_flag) values (%d,%d,'%s')";
        $sql_query_event = 'select id from alert_event where category_id = %d';
        $evnet_list = array();
        $result = db_query($sql_query_event, $alert_category);
        while ($row = db_fetch_object($result)) {
          $evnet_list[] = $row->id;
        }

        foreach ($evnet_list as $event_id) {
          $result = db_query($sql_query_exsit, $event_id, $device_type_id);
          $relation_id = 0;
          if ($row = db_fetch_object($result)) {
            $relation_id = $row->id;
          }
          if ($relation_id) {
            //udpate
            if (in_array($event_id, $enable_event_list)) {
              db_query($sql_update, 'Y', $relation_id);
            } else {
              db_query($sql_update, 'N', $relation_id);
            }
          } else {
            //insert
            if (in_array($event_id, $enable_event_list)) {
              db_query($sql_insert, $device_type_id, $event_id, 'Y');
            } else {
              db_query($sql_insert, $device_type_id, $event_id, 'N');
            }
          }
        }
      } else if ($operation_type == 'Y') {
        $alert_event = $post['alert_event'];
        $alert_delivery = $post['alert_delivery'];
        $field_app_role_list = is_array($post['field_app_role_list']) ? $post['field_app_role_list'] : array();
        $query = "select b.id from device_type_alert_template_relation a 
            join alert_message_template b on a.alert_message_template_id = b.id
          where b.alert_event_id = %d and b.alert_transport_type_id = %d
          and a.device_type_nid = %d ";
        $result = db_query($query, $alert_event, $alert_delivery, $device_type_id);
        if ($row = db_fetch_object($result)) {
          $device_type_tempalte_id = $row->id;
        }
        if (is_numeric($device_type_tempalte_id)) {
          $sql_delete = "delete from application_role_alert where device_type_alert_template_association_id = %d";
          $sql_insert = "insert into application_role_alert (application_role_pk,active_flag,device_type_alert_template_association_id) values 
              (%d,'Y',%d)";
          db_query($sql_delete, $device_type_tempalte_id);
          if (!empty($field_app_role_list)) {
            foreach ($field_app_role_list as $value) {
              db_query($sql_insert, $value, $device_type_tempalte_id);
            }
          }
        }
      }
    } else {
      $person_nid = getUserPersonNid();
      $person_alert_delivery = $post['person_alert_delivery'];
      $field_person_alert_event_list = is_array($post['field_person_alert_event_list']) ? $post['field_person_alert_event_list'] : array();
      $person_alert_event_device_scope = $post['person_alert_event_device_scope'];
      $field_person_alert_country = is_array($post['field_person_alert_country']) ? $post['field_person_alert_country'] : array();

      $sql_query_event = 'select b.id as event_id,a.id as relation_id from device_type_alert_event_relation a 
       join alert_event b on a.alert_event_id = b.id
       where b.category_id = %d and a.device_type_nid = %d';
      $result = db_query($sql_query_event, $alert_category, $device_type_id);
      $relation_arr = array();
      while ($row = db_fetch_object($result)) {
        $relation_arr[$row->event_id] = $row->relation_id;
      }
      if (!empty($relation_arr)) {
        $sql_delete_transport = 'delete from person_alert_transport where person_nid=%d and alert_category_id=%d and device_type_nid=%d';
        $sql_insert_transport = "insert into person_alert_transport (person_nid,alert_category_id,device_type_nid,alert_transport_type_id)
      values (%d,%d,%d,(select id from alert_transport_type where name='%s'))";
        db_query($sql_delete_transport, $person_nid, $alert_category, $device_type_id);
        if (!empty($person_alert_delivery)) {
          foreach ($person_alert_delivery as $value) {
            db_query($sql_insert_transport, $person_nid, $alert_category, $device_type_id, $value);
          }
        }

        $sql_delete_conutry = 'delete from person_alert_country where person_nid=%d and alert_category_id=%d and device_type_nid=%d';
        $sql_insert_conutry = "insert into person_alert_country (person_nid,alert_category_id,device_type_nid,country_nid)
      values (%d,%d,%d,%d)";
        db_query($sql_delete_conutry, $person_nid, $alert_category, $device_type_id);
        if (!empty($field_person_alert_country)) {
          foreach ($field_person_alert_country as $value) {
            db_query($sql_insert_conutry, $person_nid, $alert_category, $device_type_id, $value);
          }
        }

        $sql_delete_subscription = 'delete from {person_alert_event_subscription} where person_nid=%d and device_type_nid=%d and device_type_alert_event_relation_id = %d';
        $sql_insert_subscription = "insert into {person_alert_event_subscription} 
          (person_nid, device_type_nid, active_flag, device_scope, device_type_alert_event_relation_id) values (%d,%d,'%s','%s',%d)";
        foreach ($relation_arr as $event_id => $relation_id) {
          db_query($sql_delete_subscription, $person_nid, $device_type_id, $relation_id);
          if ($event_id == $field_person_alert_event_list[$event_id]) {
            db_query($sql_insert_subscription, $person_nid, $device_type_id, 'Y', $person_alert_event_device_scope[$event_id], $relation_id);
          } else {
            db_query($sql_insert_subscription, $person_nid, $device_type_id, 'N', $person_alert_event_device_scope[$event_id], $relation_id);
          }
        }
      }
    }
  } catch (Exception $e) {
    // Generic exception handling if something else gets thrown.
    watchdog('Alert Error', $e->getMessage(), WATCHDOG_ERROR);
    drupal_set_message(t('Settings have not been saved.'), $type = 'error', $repeat = TRUE);
  }
  drupal_set_message(t('Settings have been saved successfully.'), $type = 'status', $repeat = TRUE);
  drupal_goto('alert/config/subscribe/admin');
}

function _filter_alert_select_form($product_line = 0, $device_type_id = 0, $alert_category_id = 0) {
  $device_type_id = $device_type_id ? $device_id : check_plain($_GET['sel_device_type']); //get
  $device_type_id = $device_type_id ? $device_type_id : $_SESSION['default_dtype'];  //session
  $product_line = $product_line ? $product_line : $_SESSION['default_cot'];
  $alert_event = $_GET['alert_event'] ? check_plain($_GET['alert_event']) : '';
  $alert_state = $_GET['alert_state'] ? check_plain($_GET['alert_state']) : '';
  $form['select_device_type'] = array(
    '#type' => 'select',
    '#id' => 'sel_device_type',
    '#name' => 'sel_device_type',
    '#options' => _get_device_type_list($product_line),
    '#default_value' => $device_type_id,
    '#value' => $device_type_id,
  );
  $form['ISOCountryList'] = array(
    '#type' => 'select',
    '#id' => 'ISOCountry',
    '#name' => 'ISOCountry',
    '#options' => _get_iso_country_list(),
    '#default_value' => 'All',
  );
  $form['alert_category'] = array(
    '#type' => 'select',
    '#id' => 'alert_category',
    '#name' => 'alert_category',
    '#options' => _get_alert_category_list('yes'),
    '#default_value' => 'All',
  );
  $form['alert_event'] = array(
    '#type' => 'select',
    '#id' => 'alert_event',
    '#name' => 'alert_event',
    '#options' => _get_alert_event_list($alert_category_id, 'yes'),
    '#default_value' => $alert_event,
    '#value' => $alert_event,
  );
  $form['alert_state'] = array(
    '#type' => 'select',
    '#id' => 'alert_state',
    '#name' => 'alert_state',
    '#options' => _get_alert_state_list(),
    '#default_value' => $alert_state,
    '#value' => $alert_state,
  );
  $form['alert_delivery'] = array(
    '#type' => 'select',
    '#id' => 'alert_delivery',
    '#name' => 'alert_delivery',
    '#options' => _get_alert_delivery_list(),
    '#default_value' =>
    'All',
  );

  return $form;
}

function _get_device_type_list($product_line) {
  $rows = array();
  $query = "select b.nid,b.title from content_field_device_product_line a join node b on a.nid = b.nid and a.vid = b.vid where a.field_device_product_line_nid=%d";
  $result = db_query($query, $product_line);
  while ($row = db_fetch_object($result)) {
    $rows[$row->nid] = $row->title;
  }
  return $rows;
}

function _get_alert_state_list($status_id = 0) {
  $rows = array();
  $query = "SELECT id, name FROM {alert_state} ORDER BY weight ASC";
  if ($status_id) {
    $link = db_result(db_query("SELECT link_id FROM {alert_state} WHERE id=%d", $status_id));
    $query = "SELECT id, name FROM {alert_state} WHERE id IN (" . $link . ") ORDER BY weight ASC";
  }
  $result = db_query($query);
  while ($row = db_fetch_object($result)) {
    $rows[$row->id] = $row->name;
  }
  return $rows;
}

function _get_alert_category_list($exclude_technic = 'yes') {
  $rows = array();
  $default_cot = $_SESSION['default_cot'];
  $query = "SELECT id,name FROM {alert_category} ";
  if ($exclude_technic == 'yes') {
    $query .= " WHERE name <> 'General Notification' ";
  }
  $result = db_query($query);
  while ($row = db_fetch_object($result)) {
    // 26 means 'Infrastructure' COT.
    if ($default_cot != 26 && $row->name == 'General Notification') {
      continue;
    }
    $rows[$row->id] = $row->name;
  }
  return $rows;
}

function _get_alert_event_list($alert_category_id = 'All', $exclude_technic = 'yes') {
  $rows = array();
  $where = array();
  if ($exclude_technic == 'only') {
    $where[] = " ac.name = 'General Notification' ";
  } elseif ($exclude_technic == 'yes') {
    $where[] = " ac.name <> 'General Notification' ";
  }
  $query = "SELECT ae.id, ae.name FROM {alert_event} ae LEFT JOIN {alert_category} ac ON ae.category_id = ac.id";
  if (is_numeric($alert_category_id) && $alert_category_id) {
    $where[] = ' ae.category_id = ' . $alert_category_id;
  }
  if ($where) {
    $query .= ' WHERE ' . implode(' AND ', $where);
  }
  $result = db_query($query);
  while ($row = db_fetch_object($result)) {
    $rows[$row->id] = $row->name;
  }
  return $rows;
}

function _get_alert_delivery_list() {
  $rows = array();
  $query = "select id,name from alert_transport_type";
  $result = db_query($query);
  while ($row = db_fetch_object($result)) {
    $rows[$row->id] = $row->
      name;
  }
  return $rows;
}

function covidien_alert_get_app_role_list($alert_event = 0, $delivery = 0) {
  $device_type_id = $_GET['device_type'] ? check_plain($_GET['device_type']) : $_SESSION['default_dtype'];
  $product_line = $_SESSION['default_cot'];
  $alert_event = $alert_event ? $alert_event : check_plain($_GET['alert_event']);
  $delivery = $delivery ? $delivery : check_plain($_GET['alert_delivery']);
  $sql = "select b.nid,b.title from content_type_roles a join node b on a.nid = b.nid where a.field_role_product_line_nid=%d";
  $header = array(
    array('data' => ''),
    array('data' => t('Application Role')),
  );

  $checked = array();
  $sql_checked = "select c.id, c.application_role_pk from device_type_alert_template_relation a join alert_message_template b on a.alert_message_template_id = b.id
	join application_role_alert c on a.id = c.device_type_alert_template_association_id
	where b.alert_event_id = %d and b.alert_transport_type_id = %d
	and c.active_flag = 'Y' and a.device_type_nid = %d";

//check seleted
  $result = db_query($sql_checked, $alert_event, $delivery, $device_type_id);
  while ($row = db_fetch_object($result)) {
    $checked[$row->application_role_pk] = 'checked';
  }
//get table list
  $result = db_query($sql, $product_line);
  while ($row = db_fetch_object($result)) {
    $rows[$row->nid]['nid'] = "<input type=\"checkbox\" class=\"form-checkbox\" {$checked[$row->nid]} value=\"$row->nid\" id=\"edit-field-app_role_list-$row->nid\" name=field_app_role_list[$row->nid]\">";
    $rows[$row->nid]['title'] = $row->title;
  }

  $output = "<div style=\"float:left; position: relative; width: 45%;\">";
  $output .= "<span title=\"This field is required.\" class=\"form-required\">*</span>Candidate Application Roles";
  $output .= "<div style=\"overflow: auto; max-height: 400px;\">";
// table head need to customize
  $output .= theme_table($header, $rows, array('id' => 'left_table'));

  $output .= "</div></div>";


  $output .= "<div style=\"float:left;\"><br>";

  $output .= "<table style=\"border:0px;\"><tbody style=\"border:0px;\"><tr onclick=\"move_table_item_right('left_table','right_table');\"><td style=\"border:0px;\">";

  $output .= "<input type=\"button\" class=\"form-submit\" value=\"-->\" /> ";
  $output .= "</td></tr>";

  $output .= "<tr onclick=\"move_table_item_left('left_table','right_table');\"><td style=\"border:0px;\">";

  $output .= "<input type=\"button\" class=\"form-submit\"  value=\"<--\" /> ";
  $output .= "</td></tr>";

  $output .= "</td></tr></tbody></table></div>";

  $output .= "<div style=\"float:left; position: relative; width: 45% \"><span title=\"This field is required.\" class=\"form-required\">*</span>Selected Application Roles";
  $output .= "<div style=\"overflow: auto; max-height: 400px;\" >";

  $output .= " <table id='right_table'>
  <thead>
    <tr>
      <th></th>
      <th>Application Role</th>
    </tr>
  </thead>
  </table> ";

  $output .= "</div></div>";

  drupal_json(array('status' =>
    'success', 'data' => $output));
}

function covidien_alert_ajax_get_template_tbl($alert_event = 0, $delivery = 0) {
  $device_type_id = $_GET['device_type'] ? check_plain($_GET['device_type']) : $_SESSION['default_dtype'];
  $alert_event = $alert_event ? $alert_event : check_plain($_GET['alert_event']);
  $delivery = $delivery ? $delivery : check_plain($_GET['alert_delivery']);

  $query = "select b.id,b.name,c.name as event,d.name as delivery,b.message_subject_text as subject from device_type_alert_template_relation a 
    join alert_message_template b on a.alert_message_template_id = b.id
	join alert_event c on b.alert_event_id = c.id
	join alert_transport_type d on b.alert_transport_type_id = d.id
	where b.alert_event_id = %d and b.alert_transport_type_id = %d";
  if ($device_type_id) {
    $query .= ' and a.device_type_nid = %d';
  }
  $header = array(
    array('data' => t('Template Name')),
    array('data' => t('Alert Event')),
    array('data' => t('Delivery')),
    array('data' => t('Subject Line')),
  );

  $rows = array();
  if ($device_type_id) {
    $result = db_query($query, $alert_event, $delivery, $device_type_id);
  } else {
    $result = db_query($query, $alert_event, $delivery);
  }
  while ($row = db_fetch_object($result)) {
    $rows[$row->id]['name'] = l($row->name, 'alert/template/edit/' . $row->id);
    $rows[$row->id]['event'] = $row->event;
    $rows[$row->id]['delivery'] = $row->delivery;
    $rows[$row->id]['subject'] = $row->subject;
  }
  if (empty($rows)) {
    $hasTemplate = false;
    $rows[$row->nid]['name'] = array(
      'data' => l('No recommended message template, please create corresponding message template!', 'alert/template/list'),
      'colspan' => '4');
  } else {
    $hasTemplate = true;
  }

  $output = "<div style=\"float:left; position: relative; width: 80% \">";
  $output .= "<div style=\"overflow: auto; max-height: 400px;\">";
// table head need to customize
  $output .= theme_table($header, $rows, array('id' => 'alert_template_tbl', 'style' => 'margin-left:0px;'));
  $output .= "</div></div>";
  drupal_json(array('status' => 'success', 'hasTemplate' => $hasTemplate, 'data' => $output));
}

function covidien_alert_ajax_get_alert_event_list($alert_category = 0) {
  $alert_category = check_plain($_GET['alert_category']);
  $alert_event = $_GET['alert_event'] ? check_plain($_GET['alert_event']) : '';
  $form = array(
    '#type' => 'select',
    '#id' => 'alert_event',
    '#name' => 'alert_event',
    '#options' => _get_alert_event_list($alert_category, 'yes'),
    '#default_value' => $alert_event,
    '#value' => $alert_event,
  );
  drupal_json(array('status' => 'success', 'data' => drupal_render($form)));
}

function covidien_alert_ajax_get_alert_event_status_tbl($device_type_id = 0, $alert_category = 0) {
  $device_type_id = $device_type_id ? $device_type_id : check_plain($_GET['device_type']);
  $device_type_id = $device_type_id ? $device_type_id : $_SESSION['default_dtype'];
  $alert_category = $alert_category ? $alert_category : check_plain($_GET['alert_category']);

  $sql_query = "select a.id, a.name as event, b.name as category ,a.description from alert_event a 
  				join alert_category b on a.category_id = b.id where b.id=%d";

  $sql_checked = "select b.id from alert_category a 
  			join alert_event b on a.id = b.category_id 
  			left join device_type_alert_event_relation c on b.id = c.alert_event_id 
  			left join content_type_devicetype d on c.device_type_nid = d.nid 
  			where a.id = %d  and d.nid = %d and c.enable_flag = 'Y' ";

  $header = array(
    array('data' => t('Enable/Disable')),
    array('data' => t('Alert Event')),
    array('data' => t('Alert Category')),
    array('data' => t('Description')),
  );
  $checked = array();
  $result = db_query($sql_checked, $alert_category, $device_type_id);
  while ($row = db_fetch_object($result)) {
    $checked[$row->id] = 'checked';
  }
  $rows = array();
  $result = db_query($sql_query, $alert_category);
  while ($row = db_fetch_object($result)) {

    $rows[$row->id]['name'] = "<input type=\"checkbox\" class=\"form-checkbox\" {$checked[$row->id]} value=\"$row->id\" id=\"edit-field-alert_event_status_list-$row->id\" name=field_alert_event_status_list[$row->id]\">";
    $rows[$row->id]['event'] = $row->event;
    $rows[$row->id]['delivery'] = $row->category;
    $rows[$row->id]['subject'] = $row->description;
  }

  $output = "<div style=\"float:left; position: relative; width: 100% \">";

  $output .= "<div style=\"overflow: auto; max-height: 600px;\">";

// table head need to customize
  $output .= theme_table($header, $rows, array('id' => 'alert_event_status_tbl', 'style' => 'margin-left:0px;'));

  $output .= "</div></div>";

  drupal_json(array('status' =>
    'success', 'data' => $output));
}

function covidien_alert_ajax_get_person_alert_delivery($device_type_id = 0, $alert_category = 0) {
  $device_type_id = $device_type_id ? $device_type_id : check_plain($_GET['device_type']);
  $device_type_id = $device_type_id ? $device_type_id : $_SESSION['default_dtype'];
  $alert_category = $alert_category ? $alert_category : check_plain($_GET['alert_category']);

  $person_nid = getUserPersonNid();

  $query = "select a.name,b.id  from alert_transport_type a left join person_alert_transport b 
		on a.id = b.alert_transport_type_id
		and b.device_type_nid = %d and b.alert_category_id = %d and person_nid = %d";
  $checked = array();
  $result = db_query($query, $device_type_id, $alert_category, $person_nid);
  while ($row = db_fetch_object($result)) {
    $check_status = '';
    if ($row->id) {
      $check_status = 'checked';
    }
    $checked[$row->name] = $check_status;
  }
  $checked['status'] = 'success';

  drupal_json($checked);
}

function covidien_alert_ajax_get_person_alert_event($device_type_id = 0, $alert_category = 0) {
  global $user;
  $device_type_id = $device_type_id ? $device_type_id : check_plain($_GET['device_type']);
  $device_type_id = $device_type_id ? $device_type_id : $_SESSION['default_dtype'];
  $alert_category = $alert_category ? $alert_category : check_plain($_GET['alert_category']);

  $query = "SELECT a.id, b.enable_flag, a.name, b.id AS relation_id
			FROM {alert_event} a 
      left join {device_type_alert_event_relation} b on a.id = b.alert_event_id 
			where b.device_type_nid = %d and a.category_id = %d ";

  $header = array(
    array('data' => t('Active')),
    array('data' => t('Status From Admin Setting'), 'title' => "This status is from administrative setting. If it is 'Enable', after you activating the corresponding alert event you can recieve email when event happening. If it is 'Disable', you cannot recieve email when event happening even you activated the corresponding alert event."),
    array('data' => t('Alert Event')),
    array('data' => t('Device Scope')),
  );
  $person_nid = getUserPersonNid();
  $person_rows = array();
  if ($person_nid) {
    $person_result = db_query("SELECT active_flag, device_scope, device_type_alert_event_relation_id FROM {person_alert_event_subscription} WHERE person_nid=%d", $person_nid);
    while ($person_row = db_fetch_object($person_result)) {
      $person_rows[$person_row->device_type_alert_event_relation_id]['relation_id'] = $person_row->device_type_alert_event_relation_id;
      $person_rows[$person_row->device_type_alert_event_relation_id]['active_flag'] = $person_row->active_flag;
      $person_rows[$person_row->device_type_alert_event_relation_id]['device_scope'] = $person_row->device_scope;
    }
  }
  $device_scope_options = array('M' => 'Mine', 'A' => 'All',);
  $rows = array();
  $result = db_query($query, $device_type_id, $alert_category);
  while ($row = db_fetch_object($result)) {
    $checked = ($person_rows[$row->relation_id]['active_flag'] == 'Y') ? 'checked' : '';
    $device_scope = array(
      '#type' => 'select',
      '#id' => "person_alert_event_device_scope-" . $row->id,
      '#name' => "person_alert_event_device_scope[" . $row->id . "]",
      '#options' => $device_scope_options,
      '#value' => $person_rows[$row->relation_id]['device_scope'],
    );
    $rows[$row->id]['id'] = '<input type="checkbox" class="form-checkbox" ' . $checked . ' value="' . $row->id . '" id="edit-field-person_alert_event_list-' . $row->id . '" name=field_person_alert_event_list[' . $row->id . ']">';
    $rows[$row->id]['enable'] = $row->enable_flag == 'Y' ? 'Enable' : 'Disable';
    $rows[$row->id]['name'] = $row->name;
    $rows[$row->id]['device_scope'] = drupal_render($device_scope);
  }
  $personAlertSubscriptionEnableFlg = false;
  if (!empty($rows)) {
    $personAlertSubscriptionEnableFlg = true;
  }
  $output = "<div style=\"float:left; position: relative; width: 100% \">";
  $output .= "<div style=\"overflow: auto; max-height: 600px;\">";
// table head need to customize
  $output .= theme_table($header, $rows, array('id' => 'alert_event_status_tbl', 'style' => 'margin-left:0px;'));
  $output .= "</div></div>";

  drupal_json(array('status' => 'success', 'data' => $output, 'personAlertSubscriptionEnableFlg' => $personAlertSubscriptionEnableFlg));
}

function covidien_alert_ajax_get_person_alert_country($alert_event = 0, $alert_category = 0) {
  $device_type_id = $_GET['device_type'] ? check_plain($_GET['device_type']) : $_SESSION['default_dtype'];
  $product_line = $_SESSION['default_cot'];
  $alert_event = $alert_event ? $alert_event : check_plain($_GET['alert_event']);
  $alert_category = $alert_category ? $alert_category : check_plain($_GET['alert_category']);
  $sql = "select nid,title from node where type='country' ";
  $header = array(
    array('data' => 'Select'),
    array('data' => t('Country')),
  );
  $person_nid = getUserPersonNid();

  $sql_checked = "select a.nid from node a join person_alert_country b on a.nid = b.country_nid 
		where a.type='country' and b.device_type_nid=%d and b.alert_category_id=%d and person_nid=%d";
  $checked = array();
//check seleted
  $result = db_query($sql_checked, $device_type_id, $alert_category, $person_nid);
  while ($row = db_fetch_object($result)) {
    $checked[
      $row->nid] = 'checked';
  }
//get table list
  $result = db_query($sql, $product_line);
  while ($row = db_fetch_object($result)) {
    $rows[$row->nid]['nid'] = "<input type=\"checkbox\" class=\"form-checkbox\" {$checked[$row->nid]} value=\"$row->nid\" id=\"edit-field-person_alert_country-$row->nid\" name=field_person_alert_country[$row->nid]\">";
    $rows[$row->nid]['title'] = $row->title;
  }

  $output = "<div style=\"float:left; position: relative; width: 45%;\">";
  $output .= "<span title=\"This field is required.\" class=\"form-required\">*</span>Candidate Countries";
  $output .= "<div style=\"overflow: auto; max-height: 400px;\">";
// table head need to customize
  $output .= theme_table($header, $rows, array('id' => 'left_table'));

  $output .= "</div></div>";

  $output .= "<div style=\"float:left;\"><br>";

  $output .= "<table style=\"border:0px;\"><tbody style=\"border:0px;\"><tr onclick=\"move_table_item_right('left_table','right_table');\"><td style=\"border:0px;\">";

  $output .= "<input type=\"button\" class=\"form-submit\" value=\"-->\" /> ";
  $output .= "</td></tr>";

  $output .= "<tr onclick=\"move_table_item_left('left_table','right_table');\"><td style=\"border:0px;\">";

  $output .= "<input type=\"button\" class=\"form-submit\"  value=\"<--\" /> ";
  $output .= "</td></tr>";

  $output .= "</td></tr></tbody></table></div>";

  $output .= "<div style=\"float:left; position: relative; width: 45% \"><span title=\"This field is required.\" class=\"form-required\">*</span>Selected Countries";
  $output .= "<div style=\"overflow: auto; max-height: 400px;\" >";

  $output .= " <table id='right_table'>
  <thead>
    <tr>
      <th style=\"width:20%\" >Select</th>
      <th>Country</th>
    </tr>
  </thead>
  </table> ";

  $output .= "</div></div>";

  drupal_json(array('status' => 'success', 'data' => $output));
}

/**
 * Implements cron functioanlity.
 */
function covidien_alert_cron() {
  global $language, $user;
  covidien_update_log('Run Start ' . __FUNCTION__);

  // "((tns.schedule_date - INTERVAL tn.time_zone SECOND) + INTERVAL -5 HOUR)" means covert time to EST.
  $sql = "select tn.id notification_id, tns.id schedule_id, tn.message_text, concat(event.name,' - ', tns.subject_line) as subject, tns.internal_only_flag,tns.device_type_nid,tns.on_completion_flag 
  		from technical_notification tn join technical_notification_schedule tns on tn.id = tns.technical_notification_id
		and tn.active_status = 'Y' and tns.active_status = 'Y' 
		and ((tns.schedule_date - INTERVAL tn.time_zone SECOND) + INTERVAL -5 HOUR) <= now()  
		and tns.sent_flag = 'N'
		join alert_event event on tn.alert_event_id = event.id order by tns.schedule_date ";
  $result = db_query($sql);
  $notices = array();
  while ($row = db_fetch_object($result)) {
    $arr = array();
    $arr ['notification_id'] = $row->notification_id;
    $arr ['schedule_id'] = $row->schedule_id;
    $arr ['message'] = $row->message_text;
    $arr ['covidien_only_flag'] = $row->internal_only_flag;
    $arr ['device_type_nid'] = $row->device_type_nid;
    $arr ['on_completion_flag'] = $row->on_completion_flag;
    $arr ['subject'] = $row->subject;
    $notices [] = $arr;
  }
  if (!empty($notices)) {
    covidien_update_log('There are ' . count($notices) . ' general notifications to be sent' . __FUNCTION__);
    $mail = new Mail ();
    foreach ($notices as $notice) {
      $maillist = array();
      if (!empty($notice ['covidien_only_flag'])) {
        if ($notice ['covidien_only_flag'] == 'Y') {
          $flag = true;
        } else {
          $flag = false;
        }
        $maillist = get_covidien_user_list($flag);
      }
      if ($notice ['device_type_nid']) {
        $maillist = get_cot_mail_by_device_type($notice ['device_type_nid']);
      }
      if (empty($maillist)) {
        covidien_update_log('No recipients for [' . $notice['subject'] . ' ]');
        continue;
      }
      $info ['uid'] = $user->uid;
      $info ['name'] = 'User';
      $info ['message'] = $notice ['message'];
      $info ['to'] = $maillist;
      covidien_update_log('Send alert to :' . implode(',', $info ['to']) . ' [' . $notice['subject'] . ' ]');
      $info ['language'] = $language;
      $info ['subject'] = $notice ['subject'];

      $mailstatus = $mail->generalNotification($info);
      if ($mailstatus) {
        db_query("update technical_notification_schedule set sent_flag = 'Y' where id=%d ", $notice ['schedule_id']);
        if ($notice ['on_completion_flag'] == 'Y') {
          db_query("update technical_notification set complete_flag = 'Y' where id=%d ", $notice ['notification_id']);
        }
      }
    }
  } else {
    covidien_update_log('No general notification to be sent ' . __FUNCTION__);
  }
  covidien_update_log('Finished ' . __FUNCTION__);
}

function get_covidien_user_list($covidien_only = true) {
  $sql = "select a.field_person_username_value from content_type_person a join content_field_expiration_datetime b on a.vid = b.vid and a.nid = b.nid and b.field_expiration_datetime_value is null ";
  if ($covidien_only) {
    $sql .= " where a.field_covidien_employee_value = 'Yes' ";
  }
  $mail = array();
  $result = db_query($sql);
  while ($row = db_fetch_object($result)) {
    $mail[] = $row->field_person_username_value;
  }
  return $mail;
}

function get_cot_mail_by_device_type($device_type_nid = 0) {
  $sql = "SELECT e.field_person_username_value FROM content_field_device_product_line a join content_type_roles b on a.field_device_product_line_nid = b.field_role_product_line_nid
    and b.field_roles_description_value = 'CoT Admin' join content_field_app_role_pk c on b.nid = c.field_app_role_pk_nid
    join content_field_person_pk d on c.nid = d.nid 
    join content_type_person e on d.field_person_pk_nid = e.nid 
    join content_field_expiration_datetime f on e.vid = f.vid and e.nid = f.nid and f.field_expiration_datetime_value is null
    join content_type_person_training_record g on g.field_trainee_id_nid = d.field_person_pk_nid and g.field_active_flag_value = 0
    join content_field_device_type h on g.nid = h.nid and h.field_device_type_nid = a.nid
    where a.nid=%d ";
  $mail = array();
  $result = db_query($sql, $device_type_nid);
  while ($row = db_fetch_object($result)) {
    $mail[] = $row->field_person_username_value;
  }
  return $mail;
}
