<?php

/**
 * Implementation of hook_install().
 */
function covidien_devices_install() {
  $files = file_scan_directory(drupal_get_path('module', 'covidien_devices') . '/content_type', '.cck_import.inc');
  foreach ($files as $absolute => $file) {
    $form_state = array();
    $form_state['values']['type_name'] = '<create>';
    $fh = fopen($file->filename, 'r');
    $theData = fread($fh, filesize($file->filename));
    fclose($fh);
    $form_state['values']['macro'] = "$theData";
    drupal_execute('content_copy_import_form', $form_state);
  }
}

/**
 * Implements hook_update
 * Content type changes for ETL data
 */
function covidien_devices_update_6001() {
  module_load_include('php', 'covidien_ui', 'includes/content_copy_import_update');
  $ret = array();
  // List of new content types to import.
  //$import_new = array('sample.cck_import');
  $import_new = array();
  //Example 'contenttype.cck_import' 
  // List of content types to update.
  $import_updatearr = array(
    'device_installation.cck_import' => 'device_installation',
  );
  // For delete action update the update action array also.If the content type not deleted
  // @info: If content type deleted follow the below process
  $import_deletearr = array();
  $import_ctdeletearr = array();
  //Example 'contenttype.cck_import'=>array('field_one'),  
  $arg = array(
    'module_name' => 'covidien_devices',
    'import_new' => $import_new,
    'import_updatearr' => $import_updatearr,
    'import_deletearr' => $import_deletearr,
    'import_ctdeletearr' => $import_ctdeletearr,
  );
  covidien_contenttype_update($arg);
  return $ret;
}

/**
 * Implements hook_update
 * 9.2
 */
function covidien_devices_update_6002() {
  module_load_include('php', 'covidien_ui', 'includes/content_copy_import_update');
  $ret = array();
  // List of new content types to import.
  //$import_new = array('sample.cck_import');
  $import_new = array('device_component_upgrade_log.cck_import');
  //Example 'contenttype.cck_import' 
  // List of content types to update.
  $import_updatearr = array();
  // For delete action update the update action array also.If the content type not deleted
  // @info: If content type deleted follow the below process
  $import_deletearr = array();
  $import_ctdeletearr = array();
  //Example 'contenttype.cck_import'=>array('field_one'),  
  $arg = array(
    'module_name' => 'covidien_devices',
    'import_new' => $import_new,
    'import_updatearr' => $import_updatearr,
    'import_deletearr' => $import_deletearr,
    'import_ctdeletearr' => $import_ctdeletearr,
  );
  covidien_contenttype_update($arg);
  return $ret;
}

/**
 * Implements hook_update
 * Content type changes Device installation
 * for Phase 2
 */
function covidien_devices_update_6100() {
  module_load_include('php', 'covidien_ui', 'includes/content_copy_import_update');
  $ret = array();
  // List of new content types to import.
  //$import_new = array('sample.cck_import');
  $import_new = array();
  //Example 'contenttype.cck_import' 
  // List of content types to update.
  $import_updatearr = array(
    'device_installation.cck_import' => 'device_installation',
  );
  // For delete action update the update action array also.If the content type not deleted
  // @info: If content type deleted follow the below process
  $import_deletearr = array();
  $import_ctdeletearr = array();
  //Example 'contenttype.cck_import'=>array('field_one'),  
  $arg = array(
    'module_name' => 'covidien_devices',
    'import_new' => $import_new,
    'import_updatearr' => $import_updatearr,
    'import_deletearr' => $import_deletearr,
    'import_ctdeletearr' => $import_ctdeletearr,
  );
  covidien_contenttype_update($arg);
  return $ret;
}

// Uninstall Instruction
function covidien_devices_uninstall() {
  
}
