<?php
// $Id: privatemsg_rules.module,v 1.4.2.2 2010/10/16 07:15:49 berdir Exp $

/**
 * @file
 * Hooks and callback functions for rules.module integration.
 */

/**
 * Implements hook_rules_privatemsg_message_insert().
 */
function privatemsg_rules_privatemsg_message_insert($message) {
  foreach ($message->recipients as $recipient) {
    if ($recipient->type == 'user') {
      rules_invoke_event('privatemsg_insert', $message, $recipient);
    }
  }
}