<?php

/**
 * Implementation of hook_install().
 */
function covidien_sw_regulatory_approval_install() {

  $files = file_scan_directory(drupal_get_path('module', 'covidien_sw_regulatory_approval') . '/content_type', '.cck_import.inc');
  foreach ($files as $absolute => $file) {
    $form_state = array();
    $form_state['values']['type_name'] = '<create>';
    $fh = fopen($file->filename, 'r');
    $theData = fread($fh, filesize($file->filename));
    fclose($fh);
    $form_state['values']['macro'] = "$theData";
    drupal_execute('content_copy_import_form', $form_state);
  }
  drupal_install_schema('covidien_sw_regulatory_approval');
}

// Uninstall Instruction
function covidien_sw_regulatory_approval_uninstall() {
  
}

/**
 * Implements hook_update
 * March 2013
 */
function covidien_sw_regulatory_approval_update_6001() {
  module_load_include('php', 'covidien_ui', 'includes/content_copy_import_update');
  $ret = array();
  // List of new content types to import.
  //$import_new = array('sample.cck_import');
  $import_new = array('software_approval_unavailable.cck_import',);
  //Example 'contenttype.cck_import' 
  // List of content types to update.
  $import_updatearr = array();
  // For delete action update the update action array also.If the content type not deleted
  // @info: If content type deleted follow the below process
  $import_deletearr = array();
  $import_ctdeletearr = array(
    'software_reg_approval' => array('field_regulatory_approved_status', 'field_reg_approved_component', 'field_reg_approved_country'),
  );
  //todo:filed table creation to avoid
  //Example 'contenttype.cck_import' => array('field_one'),  
  $arg = array(
    'module_name' => 'covidien_sw_regulatory_approval',
    'import_new' => $import_new,
    'import_updatearr' => $import_updatearr,
    'import_deletearr' => $import_deletearr,
    'import_ctdeletearr' => $import_ctdeletearr,
  );
  covidien_contenttype_update($arg);
  return $ret;
}
