<?php

/**
 * Implementation of hook_install().
 */
function covidien_customer_install() {
  $files = file_scan_directory(drupal_get_path('module', 'covidien_customer') . '/content_type', '.cck_import.inc');
  foreach ($files as $absolute => $file) {
    $form_state = array();
    $form_state['values']['type_name'] = '<create>';
    $fh = fopen($file->filename, 'r');
    $theData = fread($fh, filesize($file->filename));
    fclose($fh);
    $form_state['values']['macro'] = "$theData";
    drupal_execute('content_copy_import_form', $form_state);
  }
}

// Uninstall Instruction
function covidien_customer_uninstall() {
  
}
