<?php

/**
 * @file
 * Implementation of hook_install().
 */
function covidien_access_install() {
  
}

// Uninstall Instruction
function covidien_access_uninstall() {
  
}

function covidien_access_update_6001() {
  $ret = array();
  $report = array('Device Current Configuration Report', 'Software Upgrade Report');
  $result = db_result(db_query("select type from {node_type} where type = 'product_line_report'"));
  if (empty($result)) {
    module_load_include('php', 'covidien_ui', 'includes/content_copy_import_update');
    // List of new content types to import.
    $import_new = array('product_line_report.cck_import');

    if (empty($result)) {
      module_load_include('php', 'covidien_ui', 'includes/content_copy_import_update');
      // List of new content types to import.
      $import_new = array('product_line_report.cck_import');

      $arg = array(
        'module_name' => 'covidien_reports',
        'import_new' => $import_new,
        'import_updatearr' => array(),
        'import_deletearr' => array(),
      );
      covidien_contenttype_update($arg);
    }

    $pl = db_result(db_query("SELECT nid FROM {node} WHERE title = 'Ventilator' AND type = 'product_line'"));
    foreach ($report as $val) {
      $val2 = new stdClass();
      $val2->title = "Product Line Report";
      $val2->type = "product_line_report";
      $val2->uid = 1;
      $val2->language = "en";
      $val2->field_report_product_line[0]['nid'] = $pl;
      $val2->field_report_name[0]['value'] = $val;
      node_save($val2);
    }
    return $ret;
  }
}

/**
 * sprint 7
 * @note : make use of create_plreport() and hook_update from sampledata module
 */
function covidien_access_update_6002() {
  $ret = array();
  // covidien_sampledata_install updated with the below nodes
  $report = array('Component Discrepancy Report', 'Service Records Report', 'Audit Trail Report');
  $pl = db_result(db_query("SELECT nid FROM {node} WHERE title = 'Ventilator' AND type='product_line'"));
  foreach ($report as $val) {
    $val2 = new stdClass();
    $val2->title = "Product Line Report";
    $val2->type = "product_line_report";
    $val2->uid = 1;
    $val2->language = "en";
    $val2->field_report_product_line[0]['nid'] = $pl;
    $val2->field_report_name[0]['value'] = $val;
    node_save($val2);
  }
  return $ret;
}

/**
 * sprint 7
 */
function covidien_access_update_6003() {
  $ret = array();
  db_query("UPDATE {content_type_product_line_report} SET field_report_name_value = 'Audit Trail Report' WHERE field_report_name_value = 'Audit Trial Report'");
  return $ret;
}
