<?php

/**
 * @file
 * Used software catalog module install.
 */

/**
 * Implementation of hook_install().
 */
function covidien_trade_embargo_install() {
  $sql = "CREATE TABLE IF NOT EXISTS `trade_embargo_country` (
    `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `device_id` int(11) NOT NULL DEFAULT '0' COMMENT 'content_type_device nid',
    `country_id` int(11) NOT NULL DEFAULT '0' COMMENT 'content_type_country nid',
    `device_type_id` int(11) NOT NULL DEFAULT '0' COMMENT 'content_type_devicetype nid',
    `activation_time` int(11) NOT NULL DEFAULT '0' COMMENT 'activation time',
    `expration_time` int(11) NOT NULL DEFAULT '0' COMMENT 'expration time',
    PRIMARY KEY (`id`),
    KEY `device_id` (`device_id`),
    KEY `device_type_id` (`device_type_id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8";
  db_query($sql);
  covidien_trade_embargo_update_6001();
}

/**
 * hook_uninstall()
 */
function covidien_trade_embargo_uninstall() {
  
}

//Add in Trade Embargo Tab Permission
function covidien_trade_embargo_update_6001(){
  $feature_access_node = node_load(array('title' => 'Trade Embargo Tab', 'type' => 'app_section'));
  if ($feature_access_node) {
    return;
  }
  $catalog_section_tab = db_result(db_query("SELECT nid FROM node WHERE TYPE='app_section' AND title='Catalog Management Section'"));
  $node = new stdClass();
  $node->type = 'app_section';
  $node->status = 1;
  $node->uid = 1;
  $node->title = 'Trade Embargo Tab';
  $node->field_ipermit_class[0]['value'] = 0;
  $node->field_parent_access_section[0]['nid'] = $catalog_section_tab;
  $node->field_section_name[0]['value'] = 'Trade Embargo Tab';
  $node->name = 'admin';
  //add Trade Embargo catalog Tab to access roles
  node_save($node);
  $nid = $node->nid;

  $section_option['no'] = db_result(db_query("SELECT nid FROM node WHERE TYPE='access_option' AND title='No'"));
  $node = new stdClass();
  $node->type = 'section_access_option';
  $node->status = 1;
  $node->uid = 1;
  $node->title = 'auto section_access_option Trade Embargo Tab-No';
  $node->field_access_option[0]['nid'] = $section_option['no'] ;
  $node->field_app_section[0]['nid'] = $nid;
  $node->name = 'admin';
  //add Trade Embargo catalog section to access roles
  node_save($node);

  $section_option['view'] = db_result(db_query("SELECT nid FROM node WHERE TYPE='access_option' AND title='View Only'"));
  $node = new stdClass();
  $node->type = 'section_access_option';
  $node->status = 1;
  $node->uid = 1;
  $node->title = 'auto section_access_option Trade Embargo Tab-View Only';
  $node->field_access_option[0]['nid'] = $section_option['view'] ;
  $node->field_app_section[0]['nid'] = $nid;
  $node->name = 'admin';
  //add Trade Embargo catalog section to access roles
  node_save($node);

  $section_option['edit'] = db_result(db_query("SELECT nid FROM node WHERE TYPE='access_option' AND title='View & Edit'"));
  $node = new stdClass();
  $node->type = 'section_access_option';
  $node->status = 1;
  $node->uid = 1;
  $node->title = 'auto section_access_option Trade Embargo Tab-View & Edit';
  $node->field_access_option[0]['nid'] = $section_option['edit'] ;
  $node->field_app_section[0]['nid'] = $nid;
  $node->name = 'admin';
  //add Trade Embargo catalog section to access roles
  node_save($node);

}