<?php include_once('includes/header.php');?>
<?php include_once('includes/news-banner.php');?>
<table cellspacing="0" cellpadding="0" width="1002" align="center">
  <tbody>
	<tr>
	  <td valign="top" align="left" width="218" background="images/leftb.gif">
		<?php include_once('includes/news-left.php');?>
	  </td>
	  <td valign="top">
		<table cellspacing="0" cellpadding="0" width="100%" border="0">        <tbody>        <tr>          <td align="right"><img height="9" alt="" src="images/about_04.jpg" width="784"></td></tr>        <tr>          <td>            <table height="30" cellspacing="0" cellpadding="0" width="784" border="0">              <tbody>              <tr>                <td width="26"><img height="30" alt="" src="images/about_06.jpg" width="26"></td>                <td align="left" width="739" background="images/about_09.jpg">                  <table cellspacing="0" cellpadding="0" align="left" border="0">                    <tbody>                    <tr>                      <td class="daa" background="images/about_07.jpg" height="30">首页 &gt; 新闻动态 &gt; 视频中心</td>                      <td><img height="30" alt="" src="images/about_08.jpg" width="17"></td></tr></tbody></table></td>                <td width="19"><img height="30" alt="" src="images/about_11.jpg" width="19"></td></tr></tbody></table></td></tr>        <tr>          <td background="images/rightbg.gif">            <table cellspacing="0" cellpadding="0" width="784" border="0">              <tbody>              <tr>                <td valign="top" align="middle">                  <table cellspacing="0" cellpadding="0" width="94%" align="center" border="0">                    <tbody>                    <tr>                      <td valign="top">&nbsp;</td></tr>                    <tr>                      <td valign="top" align="middle"><p><object id="MediaPlayer1" height="391" width="551" classid="CLSID:6BF52A52-394A-11d3-B153-00C04F79FAA6"><param name="URL" value="mtv/qifan.WMV"><param name="rate" value="1"><param name="balance" value="1"><param name="currentPosition" value="0"><param name="defaultFrame" value=""><param name="playCount" value="1"><param name="autoStart" value="-1"><param name="currentMarker" value="0"><param name="invokeURLs" value="-1"><param name="baseURL" value=""><param name="volume" value="100"><param name="mute" value="0"><param name="uiMode" value="none"><param name="stretchToFit" value="0"><param name="windowlessVideo" value="0"><param name="enabled" value="-1"><param name="enableContextMenu" value="-1"><param name="fullScreen" value="0"><param name="SAMIStyle" value=""><param name="SAMILang" value=""><param name="SAMIFilename" value=""><param name="captioningID" value=""><param name="AudioStream" value="-1"><param name="AutoSize" value="-1"></object></p></td></tr>                    <tr>                      <td valign="top" align="middle"><font color="#666666">视频加载中，请耐心等待……</font></td></tr>                    <tr>                      <td valign="top">&nbsp;</td></tr></tbody></table></td>                <td valign="top" width="5"><img alt="" src="images/about_13.jpg" width="5"></td></tr></tbody></table></td></tr></tbody></table>
	  </td>
	</tr>
  </tbody>
</table><?php include_once('includes/footer.php');?>

