<?php

/**
 * @file
 * Implementation of hook_install().
 */
function covidien_activity_install() {
  if (db_table_exists('activity_log') == FALSE) {
    drupal_install_schema('covidien_activity');
  }
}

// Uninstall Instruction
function covidien_activity_uninstall() {
  
}

function covidien_activity_update_6001() {
  $ret = array();

  $result = db_query("SELECT * FROM {watchdog} WHERE type = 'Device'");
  while ($row = db_fetch_object($result)) {
    $wid = $row->wid;
    $variables = unserialize($row->variables);
    $role = $variables['%role'];
    $device_name = $variables['%device_name'];
    if (is_array($variables[6])) {
      if (empty($variables[6]['%device_name'])) {
        $device = '';
      } else {
        $device = $variables[6]['%device_name'];
      }

      if (empty($variables[7]['%serial_number'])) {
        $serial = '';
      } else {
        $serial = $variables[7]['%serial_number'];
      }
      update_sql("UPDATE {watchdog} SET variables = '" . serialize(array('%device_name' => $device, '%serial_number' => $serial)) . "' WHERE wid = '" . $wid . "'");
    } else {
      $variables = $row->variables;
      if ($variables == "N;") {
        update_sql("UPDATE {watchdog} SET variables = '" . serialize(array('%device_name' => '', '%serial_number' => '')) . "' WHERE wid = '" . $wid . "'");
      }
      if (empty($device_name)) {
        update_sql("UPDATE {watchdog} SET variables = '" . serialize(array('%device_name' => '', '%serial_number' => '')) . "' WHERE wid = '" . $wid . "'");
      }
    }

    if (!empty($role)) {
      $serial = '';
      $device = '';
      update_sql("UPDATE {watchdog} SET variables = '" . serialize(array('%device_name' => $device, '%serial_number' => $serial)) . "' WHERE wid = '" . $wid . "'");
    }
  }
  return $ret;
}

function covidien_activity_update_6002() {
  $ret = array();
  global $drupal_password_expiration_day;
  variable_set('password_day', $drupal_password_expiration_day);
  return $ret;
}

/**
 *  Sprint - 7
 *  Install Custom table activity_log
 */
function covidien_activity_update_6003() {
  $ret = array();
  if (db_table_exists('activity_log') == FALSE) {
    drupal_install_schema('covidien_activity');
  }
  return $ret;
}

function covidien_activity_schema() {
  $schema['activity_log'] = array(
    'fields' => array(
      'aid' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'nid' => array(
        'type' => 'int',
        'length' => 11,
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => '1',
      ),
      'activity_type' => array(
        'type' => 'varchar',
        'length' => 100,
        'unsigned' => FALSE,
        'not null' => TRUE,
        'default' => '',
      ),
      'message' => array(
        'type' => 'text',
        'default' => '',
      ),
      'device' => array(
        'type' => 'varchar',
        'length' => 255,
        'unsigned' => FALSE,
        'not null' => TRUE,
        'default' => '',
      ),
      'device_serial' => array(
        'type' => 'varchar',
        'length' => 255,
        'unsigned' => FALSE,
        'not null' => TRUE,
        'default' => '',
      ),
      'arguments' => array(
        'type' => 'text',
        'default' => '',
      ),
      'ip_address' => array(
        'type' => 'varchar',
        'length' => 50,
        'unsigned' => FALSE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'logtime' => array(
        'type' => 'varchar',
        'length' => 50,
        'unsigned' => FALSE,
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'primary key' => array('aid'),
  );
  return $schema;
}
